apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars-rover-fleet-tracker.name" . }}
  labels:
    {{- include "mars-rover-fleet-tracker.labels" . | nindent 4 }}
    prometheus: {{ .Values.service.prometheus }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    {{- include "mars-rover-fleet-tracker.selectorLabels" . | nindent 4 }}
