pipeline {

    parameters {
        string(name: 'AWS_REGION', description: 'AWS Region', defaultValue: 'us-east-1', trim: true)
        string(name: 'ENVIRONMENT', description: 'Environment (dev, staging, prod)', defaultValue: 'dev', trim: true)
    }



    agent any
    
    stages {
        stage("Clone code from GitHub") {
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'GITHUB_CREDENTIALS', url: 'https://github.com/axelfulop/avantio-axel-devops-challenge']])
                }
            }
        }
     
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t axelfulop123/mars-rover-fleet-management .'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh 'npm install'
                    sh 'npm run test:e2e'
                }
            }
        }

        stage('Deploy Docker Image to DockerHub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'docker_pw', variable: 'docker_pw')]) {
                        sh 'docker login -u axelfulop123 -p ${docker_pw}'
                        sh 'docker push axelfulop123/mars-rover-fleet-management'
                    }
                }   
            }
        }
         
        stage('Deploying Helm Chart on EKS') {
            steps {
                script {
                    def awsRegion = params.AWS_REGION
                    def environment = params.ENVIRONMENT
                    withCredentials([string(credentialsId: '${environment}_role_account', variable: 'role_account_id')]) {
                    withAWS(roleAccount:'role_account_id', role:'${environment}Role', region:'${awsRegion}') {
                    sh 'aws eks update-kubeconfig --name ${environment}-${awsRegion}-eks-cluster'
                    }
                    }
                    def releaseExists = sh(script: "helm list -q | grep mars-rover-fleet-management", returnStatus: true) == 0

                    if (releaseExists) {
                        // Upgrade Helm chart
                        sh 'helm upgrade mars-rover-fleet-management ./helm'
                    } else {
                        // Install Helm chart
                        sh 'helm install mars-rover-fleet-management ./helm'
                        sh 'helm repo add prometheus-community https://prometheus-community.github.io/helm-charts'
                        sh 'helm install prometheus prometheus-community/prometheus'
                    }
                }
            }
        }
    }
}
