# Default values for mars-rover-fleet-tracker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: axelfulop123/mars-rover-fleet-management
  pullPolicy: Always
  tag: "latest"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: mars-service
  type: ClusterIP
  port: 3000
  targetPort: 3000


monitoring:
  prometheus: prometheus
  interval: 30s

tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mars:
  port: 3000